### ISSUE TITLE
Django 1.7 not supported?

### ISSUE THREAD

**Issue by rapilabs** [ouhouhsami/django-progressbarupload#10]
I'm using Django 1.7 with django-progressbarupload 0.1.6 and am getting the following error:

```
new_file() takes at most 6 arguments (7 given)
```

**Comment by naggie** [comment]
https://github.com/ouhouhsami/django-progressbarupload/pull/9

**Comment by strycore** [comment]
please consider releasing version 0.1.7 with this fix included as the current version available on pypi doesn't support recent versions of Django.

**Comment by Flimm** [comment]
That pull request has been merged.

**Comment by SebCorbin** [comment]
Released 0.1.17
