### ISSUE TITLE
Django 1.8 ImportError: cannot import name 'patterns'

### ISSUE THREAD

**Issue by Arytas** [ouhouhsami/django-progressbarupload#19]
if i try to start my server after configure the progress bar settigns i get this error

```
File ".../venv/lib/python3.5/site-packages/progressbarupload/urls.py", line 2, in <module>
    from django.conf.urls import patterns, url, include
ImportError: cannot import name 'patterns'
```

this error occures cause i use Django 1.8 and the pattens() function is deprecated sind version 1.8
(see https://docs.djangoproject.com/en/1.9/ref/urls/#patterns)

can u maybe upgrade the url settings in the progressbarupload/urls.py ?

**Comment by SebCorbin** [comment]
This should be fixed in the latest version
